# Generated by Django 3.2.13 on 2022-05-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrucciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_A', models.CharField(max_length=200)),
                ('coment_A', models.CharField(max_length=500)),
                ('image_A', models.ImageField(blank=True, upload_to='instrucciones_A/%Y/%m/%d')),
                ('Title_B', models.CharField(max_length=200)),
                ('coment_B', models.CharField(max_length=500)),
                ('image_B', models.ImageField(blank=True, upload_to='instrucciones_B/%Y/%m/%d')),
                ('Title_C', models.CharField(max_length=200)),
                ('coment_C', models.CharField(max_length=500)),
                ('image_C', models.ImageField(blank=True, upload_to='instrucciones_C/%Y/%m/%d')),
                ('Title_D', models.CharField(max_length=200)),
                ('coment_D', models.CharField(max_length=500)),
                ('image_D', models.ImageField(blank=True, upload_to='instrucciones_D/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Subject test',
                'verbose_name_plural': 'Subjects tests',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='test/%Y/%m/%d')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('correct', models.BooleanField(default=True)),
                ('subject_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses_exams.subjecttest')),
            ],
            options={
                'ordering': ('question',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
