# Generated by Django 3.2.13 on 2022-05-26 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inscription', models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripción')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('CI', models.IntegerField(blank=True, null=True, verbose_name='Número de Cedula')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('tel', models.BigIntegerField(blank=True, null=True, verbose_name='Número de Telefono')),
                ('cel', models.BigIntegerField(blank=True, null=True, verbose_name='Número de Celular')),
                ('course_type', models.CharField(blank=True, choices=[('R', 'Regular'), ('I', 'Intensivo'), ('E', 'Especial'), ('P', 'Practica')], max_length=1, null=True, verbose_name='Tipo de Curso a Tomar')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exams_resultsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correct', models.PositiveIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.profile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_results_items', to='courses_exams.test')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
