# Generated by Django 3.2.13 on 2022-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220524_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número de Celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número de Telefono'),
        ),
    ]
